### ISSUE TITLE
Passing next state inside exit method

### ISSUE THREAD

**Issue by RedHeadIvan** [Ed-ward/Binstate#8]
It would be nice to add some mechanics to get next state inside exit action, because FSM behaviour may differs depends on state which transition to. Currently use additional states between my basic states to customize exit action, but  it makes code less readable and I think it might be unsafe.

![example](https://user-images.githubusercontent.com/43894415/177116251-8adf720d-d301-4d70-a943-937b3ff08935.jpg)

Maybe it could be made by enchancing functionality of IStateController with NextState property and overloading OnExit same as OnEnter

**Comment by Ed-Pavlov** [comment]
There are overloads of `AddTransition` methods accepting a callback for desired behaviour.

```
ITransitions AddTransition(TEvent @event, TState stateId, Action? action = null);
ITransitions<T> AddTransition(TEvent @event, TState stateId, Action<T> action);
```
For example see `TransitionTest.should_call_action_on_transition_between_exit_and_enter`
```
    builder
           .DefineState(Initial)
           .OnExit(onExitInitial)
           .AddTransition(GoToStateX, StateX, onTransit);
```
The passed callback (onTransit) will be called after all `OnExit` and before all `OnEnter` methods.

**Comment by RedHeadIvan** [comment]
Thanks, miss this feature
But will it works for reentrancy? Seems like I should write something like that
```
.DefineState(States.ThisState)
.AddTransition(Events.Event, States.ThisState, Handler)
.AllowReentrancy(Events.Event);
```
or

```
.DefineState(States.ThisState)
.AddTransition(Events.Event, States.ThisState, Handler);
```

**Comment by Ed-Pavlov** [comment]
The second one should work fine.

In fact `AllowReentrancy` is a shortcut for such registration, as you have already guessed.
```
.DefineState(States.ThisState)
.AddTransition(Events.Event, States.ThisState)
```
